cc_binary(
    name = "abt",
    srcs = [
        "cpp/abt/build.cpp",
        "cpp/abt/disas.cpp",
        "cpp/abt/main.cpp",
        "cpp/abt/ood.cpp",
        "cpp/abt/opt.cpp",
        "cpp/abt/scan.cpp",
        "cpp/gen/abt_gen.cpp",
        "include/abt.h",
        "include/gen/abt_gen.h",
        "include/gen/abt_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "abt_md",
    srcs = [
        "cpp/abt_md/file_section.cpp",
        "cpp/abt_md/main.cpp",
        "cpp/abt_md/mdsection.cpp",
        "cpp/gen/abt_md_gen.cpp",
        "include/abt_md.h",
        "include/gen/abt_md_gen.h",
        "include/gen/abt_md_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_amcdb",
        ":lib_prot",
    ],
)

cc_binary(
    name = "acr",
    srcs = [
        "cpp/acr/check.cpp",
        "cpp/acr/createrec.cpp",
        "cpp/acr/err.cpp",
        "cpp/acr/eval.cpp",
        "cpp/acr/git.cpp",
        "cpp/acr/load.cpp",
        "cpp/acr/main.cpp",
        "cpp/acr/print.cpp",
        "cpp/acr/query.cpp",
        "cpp/acr/select.cpp",
        "cpp/acr/verb.cpp",
        "cpp/acr/write.cpp",
        "cpp/gen/acr_gen.cpp",
        "include/acr.h",
        "include/gen/acr_gen.h",
        "include/gen/acr_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_amcdb",
    ],
)

cc_binary(
    name = "acr_compl",
    srcs = [
        "cpp/acr_compl/main.cpp",
        "cpp/acr_compl/shell.cpp",
        "cpp/gen/acr_compl_gen.cpp",
        "include/acr_compl.h",
        "include/gen/acr_compl_gen.h",
        "include/gen/acr_compl_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "acr_dm",
    srcs = [
        "cpp/acr_dm/acr_dm.cpp",
        "cpp/gen/acr_dm_gen.cpp",
        "include/acr_dm.h",
        "include/gen/acr_dm_gen.h",
        "include/gen/acr_dm_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "acr_ed",
    srcs = [
        "cpp/acr_ed/ctype.cpp",
        "cpp/acr_ed/field.cpp",
        "cpp/acr_ed/finput.cpp",
        "cpp/acr_ed/main.cpp",
        "cpp/acr_ed/srcfile.cpp",
        "cpp/acr_ed/ssimfile.cpp",
        "cpp/acr_ed/target.cpp",
        "cpp/acr_ed/unittest.cpp",
        "cpp/gen/acr_ed_gen.cpp",
        "include/acr_ed.h",
        "include/gen/acr_ed_gen.h",
        "include/gen/acr_ed_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_binary(
    name = "acr_in",
    srcs = [
        "cpp/acr_in/acr_in.cpp",
        "cpp/acr_in/data.cpp",
        "cpp/gen/acr_in_gen.cpp",
        "include/acr_in.h",
        "include/gen/acr_in_gen.h",
        "include/gen/acr_in_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "acr_my",
    srcs = [
        "cpp/acr_my/acr_my.cpp",
        "cpp/gen/acr_my_gen.cpp",
        "include/gen/acr_my_gen.h",
        "include/gen/acr_my_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "algo_lib",
    srcs = [
        "cpp/gen/_gen.cpp",
        "cpp/gen/algo_gen.cpp",
        "cpp/gen/algo_lib_gen.cpp",
        "cpp/gen/command_gen.cpp",
        "cpp/gen/dev_gen.cpp",
        "cpp/gen/dmmeta_gen.cpp",
        "cpp/gen/report_gen.cpp",
        "cpp/lib/algo/arg.cpp",
        "cpp/lib/algo/backtrace.cpp",
        "cpp/lib/algo/base64.cpp",
        "cpp/lib/algo/cpu_hz.cpp",
        "cpp/lib/algo/crc32.cpp",
        "cpp/lib/algo/decimal.cpp",
        "cpp/lib/algo/errtext.cpp",
        "cpp/lib/algo/file.cpp",
        "cpp/lib/algo/fmt.cpp",
        "cpp/lib/algo/iohook.cpp",
        "cpp/lib/algo/lib.cpp",
        "cpp/lib/algo/line.cpp",
        "cpp/lib/algo/lockfile.cpp",
        "cpp/lib/algo/mmap.cpp",
        "cpp/lib/algo/prlog.cpp",
        "cpp/lib/algo/regx.cpp",
        "cpp/lib/algo/string.cpp",
        "cpp/lib/algo/time.cpp",
        "cpp/lib/algo/timehook.cpp",
        "cpp/lib/algo/tstamp.cpp",
        "cpp/lib/algo/txttbl.cpp",
        "cpp/lib/algo/u128.cpp",
        "cpp/lib/algo/win32.cpp",
        "include/algo.h",
        "include/algo.inl.h",
        "include/define.h",
        "include/gen/_gen.h",
        "include/gen/_gen.inl.h",
        "include/gen/algo_gen.h",
        "include/gen/algo_gen.inl.h",
        "include/gen/algo_lib_gen.h",
        "include/gen/algo_lib_gen.inl.h",
        "include/gen/command_gen.h",
        "include/gen/command_gen.inl.h",
        "include/gen/dev_gen.h",
        "include/gen/dev_gen.inl.h",
        "include/gen/dmmeta_gen.h",
        "include/gen/dmmeta_gen.inl.h",
        "include/gen/ietf_gen.h",
        "include/gen/ietf_gen.inl.h",
        "include/gen/report_gen.h",
        "include/gen/report_gen.inl.h",
        "include/sha.h",
        "include/sysincl.h",
        "include/typedef.h",
        "include/u128.h",
        "include/win32.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-ldl",
        "-lm",
        "-lstdc++",
    ],
    deps = [
    ],
)

cc_binary(
    name = "amc",
    srcs = [
        "cpp/amc/alias.cpp",
        "cpp/amc/avl.cpp",
        "cpp/amc/base.cpp",
        "cpp/amc/bheap.cpp",
        "cpp/amc/bitfld.cpp",
        "cpp/amc/bitset.cpp",
        "cpp/amc/blkpool.cpp",
        "cpp/amc/cget.cpp",
        "cpp/amc/charset.cpp",
        "cpp/amc/checkxref.cpp",
        "cpp/amc/cmp.cpp",
        "cpp/amc/concat.cpp",
        "cpp/amc/count.cpp",
        "cpp/amc/cppfunc.cpp",
        "cpp/amc/ctype.cpp",
        "cpp/amc/delptr.cpp",
        "cpp/amc/dflt.cpp",
        "cpp/amc/disp/call.cpp",
        "cpp/amc/disp/casetype.cpp",
        "cpp/amc/disp/filter.cpp",
        "cpp/amc/disp/main.cpp",
        "cpp/amc/disp/msg.cpp",
        "cpp/amc/disp/print.cpp",
        "cpp/amc/disp/read.cpp",
        "cpp/amc/enum.cpp",
        "cpp/amc/exec.cpp",
        "cpp/amc/fast.cpp",
        "cpp/amc/fbuf.cpp",
        "cpp/amc/fcast.cpp",
        "cpp/amc/fcmap.cpp",
        "cpp/amc/fconst.cpp",
        "cpp/amc/fdec.cpp",
        "cpp/amc/field.cpp",
        "cpp/amc/func.cpp",
        "cpp/amc/fwddecl.cpp",
        "cpp/amc/gen.cpp",
        "cpp/amc/global.cpp",
        "cpp/amc/gsymbol.cpp",
        "cpp/amc/hook.cpp",
        "cpp/amc/include.cpp",
        "cpp/amc/inlary.cpp",
        "cpp/amc/io.cpp",
        "cpp/amc/lary.cpp",
        "cpp/amc/llist.cpp",
        "cpp/amc/lpool.cpp",
        "cpp/amc/main.cpp",
        "cpp/amc/malloc.cpp",
        "cpp/amc/msgcurs.cpp",
        "cpp/amc/nstype.cpp",
        "cpp/amc/numstr.cpp",
        "cpp/amc/opt.cpp",
        "cpp/amc/outfile.cpp",
        "cpp/amc/pmask.cpp",
        "cpp/amc/pnew.cpp",
        "cpp/amc/pool.cpp",
        "cpp/amc/print.cpp",
        "cpp/amc/protocol.cpp",
        "cpp/amc/ptr.cpp",
        "cpp/amc/ptrary.cpp",
        "cpp/amc/query.cpp",
        "cpp/amc/read.cpp",
        "cpp/amc/regx.cpp",
        "cpp/amc/sbrk.cpp",
        "cpp/amc/signature.cpp",
        "cpp/amc/size.cpp",
        "cpp/amc/smallstr.cpp",
        "cpp/amc/sort.cpp",
        "cpp/amc/step.cpp",
        "cpp/amc/struct.cpp",
        "cpp/amc/substr.cpp",
        "cpp/amc/tableid.cpp",
        "cpp/amc/tary.cpp",
        "cpp/amc/tclass.cpp",
        "cpp/amc/thash.cpp",
        "cpp/amc/tpool.cpp",
        "cpp/amc/trace.cpp",
        "cpp/amc/upptr.cpp",
        "cpp/amc/val.cpp",
        "cpp/amc/varlen.cpp",
        "cpp/gen/amc_gen.cpp",
        "include/amc.h",
        "include/gen/amc_gen.h",
        "include/gen/amc_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-lcrypto",
        "-lssl",
    ],
    deps = [
        ":algo_lib",
        ":lib_amcdb",
    ],
)

cc_binary(
    name = "amc_gc",
    srcs = [
        "cpp/amc/amc_gc.cpp",
        "cpp/gen/amc_gc_gen.cpp",
        "include/gen/amc_gc_gen.h",
        "include/gen/amc_gc_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "amc_vis",
    srcs = [
        "cpp/amc/amc_vis.cpp",
        "cpp/gen/amc_vis_gen.cpp",
        "include/gen/amc_vis_gen.h",
        "include/gen/amc_vis_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "ams_cat",
    srcs = [
        "cpp/ams/ams_cat.cpp",
        "cpp/gen/ams_cat_gen.cpp",
        "include/ams_cat.h",
        "include/gen/ams_cat_gen.h",
        "include/gen/ams_cat_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ams",
    ],
)

cc_binary(
    name = "ams_sendtest",
    srcs = [
        "cpp/ams_sendtest.cpp",
        "cpp/gen/ams_sendtest_gen.cpp",
        "include/ams_sendtest.h",
        "include/gen/ams_sendtest_gen.h",
        "include/gen/ams_sendtest_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ams",
    ],
)

cc_binary(
    name = "apm",
    srcs = [
        "cpp/apm/annotate.cpp",
        "cpp/apm/check.cpp",
        "cpp/apm/diff.cpp",
        "cpp/apm/install.cpp",
        "cpp/apm/main.cpp",
        "cpp/apm/push.cpp",
        "cpp/apm/rec.cpp",
        "cpp/apm/remove.cpp",
        "cpp/apm/reset.cpp",
        "cpp/apm/show.cpp",
        "cpp/apm/update.cpp",
        "cpp/gen/apm_gen.cpp",
        "include/apm.h",
        "include/gen/apm_gen.h",
        "include/gen/apm_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ctype",
        ":lib_git",
        ":lib_prot",
    ],
)

cc_binary(
    name = "aqlite",
    srcs = [
        "cpp/aqlite/aqlite.cpp",
        "cpp/gen/aqlite_gen.cpp",
        "include/aqlite.h",
        "include/gen/aqlite_gen.h",
        "include/gen/aqlite_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
        ":lib_sqlite",
    ],
)

cc_binary(
    name = "atf_amc",
    srcs = [
        "cpp/atf_amc/atree.cpp",
        "cpp/atf_amc/bheap.cpp",
        "cpp/atf_amc/bigend.cpp",
        "cpp/atf_amc/bitfld.cpp",
        "cpp/atf_amc/bitset.cpp",
        "cpp/atf_amc/cascdel.cpp",
        "cpp/atf_amc/cdlist.cpp",
        "cpp/atf_amc/cleanup.cpp",
        "cpp/atf_amc/cmp.cpp",
        "cpp/atf_amc/cslist.cpp",
        "cpp/atf_amc/delptr.cpp",
        "cpp/atf_amc/dispatch.cpp",
        "cpp/atf_amc/exec.cpp",
        "cpp/atf_amc/fbuf.cpp",
        "cpp/atf_amc/fconst.cpp",
        "cpp/atf_amc/fstep.cpp",
        "cpp/atf_amc/gsymbol.cpp",
        "cpp/atf_amc/hook.cpp",
        "cpp/atf_amc/inlary.cpp",
        "cpp/atf_amc/lary.cpp",
        "cpp/atf_amc/lineiter.cpp",
        "cpp/atf_amc/lpool.cpp",
        "cpp/atf_amc/main.cpp",
        "cpp/atf_amc/msgcurs.cpp",
        "cpp/atf_amc/numstr.cpp",
        "cpp/atf_amc/opt.cpp",
        "cpp/atf_amc/pmask.cpp",
        "cpp/atf_amc/ptrary.cpp",
        "cpp/atf_amc/readstr.cpp",
        "cpp/atf_amc/sort.cpp",
        "cpp/atf_amc/strconv.cpp",
        "cpp/atf_amc/tary.cpp",
        "cpp/atf_amc/thash.cpp",
        "cpp/atf_amc/varlen.cpp",
        "cpp/atf_amc/zdlist.cpp",
        "cpp/atf_amc/zslist.cpp",
        "cpp/gen/atf_amc_gen.cpp",
        "include/atf_amc.h",
        "include/gen/atf_amc_gen.h",
        "include/gen/atf_amc_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_exec",
        ":lib_json",
        ":lib_prot",
    ],
)

cc_binary(
    name = "atf_ci",
    srcs = [
        "cpp/atf_ci/acr_ed.cpp",
        "cpp/atf_ci/apm.cpp",
        "cpp/atf_ci/bootstrap.cpp",
        "cpp/atf_ci/cppcheck.cpp",
        "cpp/atf_ci/main.cpp",
        "cpp/atf_ci/src.cpp",
        "cpp/atf_ci/ssim.cpp",
        "cpp/gen/atf_ci_gen.cpp",
        "include/atf_ci.h",
        "include/gen/atf_ci_gen.h",
        "include/gen/atf_ci_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ctype",
        ":lib_git",
        ":lib_prot",
    ],
)

cc_binary(
    name = "atf_cmdline",
    srcs = [
        "cpp/atf_cmdline/atf_cmdline.cpp",
        "cpp/gen/atf_cmdline_gen.cpp",
        "include/atf_cmdline.h",
        "include/gen/atf_cmdline_gen.h",
        "include/gen/atf_cmdline_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "atf_comp",
    srcs = [
        "cpp/atf_comp/edit.cpp",
        "cpp/atf_comp/main.cpp",
        "cpp/atf_comp/read.cpp",
        "cpp/gen/atf_comp_gen.cpp",
        "include/atf_comp.h",
        "include/gen/atf_comp_gen.h",
        "include/gen/atf_comp_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ctype",
        ":lib_prot",
    ],
)

cc_binary(
    name = "atf_cov",
    srcs = [
        "cpp/atf_cov/atf_cov.cpp",
        "cpp/gen/atf_cov_gen.cpp",
        "include/atf_cov.h",
        "include/gen/atf_cov_gen.h",
        "include/gen/atf_cov_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "atf_fuzz",
    srcs = [
        "cpp/atf_fuzz/atf_fuzz.cpp",
        "cpp/gen/atf_fuzz_gen.cpp",
        "include/atf_fuzz.h",
        "include/gen/atf_fuzz_gen.h",
        "include/gen/atf_fuzz_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_binary(
    name = "atf_gcli",
    srcs = [
        "cpp/atf/atf_gcli.cpp",
        "cpp/gen/atf_gcli_gen.cpp",
        "include/atf_gcli.h",
        "include/gen/atf_gcli_gen.h",
        "include/gen/atf_gcli_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_binary(
    name = "atf_nrun",
    srcs = [
        "cpp/atf_nrun/atf_nrun.cpp",
        "cpp/gen/atf_nrun_gen.cpp",
        "include/atf_nrun.h",
        "include/gen/atf_nrun_gen.h",
        "include/gen/atf_nrun_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "atf_unit",
    srcs = [
        "cpp/atf_unit/acr.cpp",
        "cpp/atf_unit/algo_fmt.cpp",
        "cpp/atf_unit/algo_lib.cpp",
        "cpp/atf_unit/algo_txttbl.cpp",
        "cpp/atf_unit/ams.cpp",
        "cpp/atf_unit/bash.cpp",
        "cpp/atf_unit/charset.cpp",
        "cpp/atf_unit/decimal.cpp",
        "cpp/atf_unit/fm.cpp",
        "cpp/atf_unit/lib_ams.cpp",
        "cpp/atf_unit/lib_exec.cpp",
        "cpp/atf_unit/lib_json.cpp",
        "cpp/atf_unit/lib_sql.cpp",
        "cpp/atf_unit/line.cpp",
        "cpp/atf_unit/lockfile.cpp",
        "cpp/atf_unit/main.cpp",
        "cpp/atf_unit/parsenum.cpp",
        "cpp/atf_unit/regx.cpp",
        "cpp/atf_unit/string.cpp",
        "cpp/atf_unit/time.cpp",
        "cpp/atf_unit/tuple.cpp",
        "cpp/gen/atf_unit_gen.cpp",
        "include/atf_unit.h",
        "include/gen/atf_unit_gen.h",
        "include/gen/atf_unit_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":lib_ams",
        ":lib_exec",
        ":lib_fm",
        ":lib_json",
        ":lib_sql",
    ],
)

cc_binary(
    name = "bash2html",
    srcs = [
        "cpp/bash2html.cpp",
        "cpp/gen/bash2html_gen.cpp",
        "include/bash2html.h",
        "include/gen/bash2html_gen.h",
        "include/gen/bash2html_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "bzg",
    srcs = [
        "cpp/bzg/bzg.cpp",
        "cpp/gen/bzg_gen.cpp",
        "include/bzg.h",
        "include/gen/bzg_gen.h",
        "include/gen/bzg_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_binary(
    name = "gcache",
    srcs = [
        "cpp/gcache/gcache.cpp",
        "cpp/gen/gcache_gen.cpp",
        "include/gcache.h",
        "include/gen/gcache_gen.h",
        "include/gen/gcache_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-lcrypto",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "gcli",
    srcs = [
        "cpp/gcli/git.cpp",
        "cpp/gcli/gtblact.cpp",
        "cpp/gcli/help.cpp",
        "cpp/gcli/issue.cpp",
        "cpp/gcli/main.cpp",
        "cpp/gcli/milestone.cpp",
        "cpp/gcli/mr.cpp",
        "cpp/gcli/note.cpp",
        "cpp/gcli/repo.cpp",
        "cpp/gcli/rest.cpp",
        "cpp/gcli/search.cpp",
        "cpp/gcli/user.cpp",
        "cpp/gen/gcli_gen.cpp",
        "include/gcli.h",
        "include/gen/gcli_gen.h",
        "include/gen/gcli_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-lcurl",
    ],
    deps = [
        ":algo_lib",
        ":lib_json",
        ":lib_prot",
    ],
)

cc_library(
    name = "lib_amcdb",
    srcs = [
        "cpp/gen/amcdb_gen.cpp",
        "cpp/gen/lib_amcdb_gen.cpp",
        "cpp/lib_amcdb/lib_amcdb.cpp",
        "include/gen/amcdb_gen.h",
        "include/gen/amcdb_gen.inl.h",
        "include/gen/lib_amcdb_gen.h",
        "include/gen/lib_amcdb_gen.inl.h",
        "include/lib_amcdb.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_ams",
    srcs = [
        "cpp/gen/lib_ams_gen.cpp",
        "cpp/lib_ams/expect.cpp",
        "cpp/lib_ams/file.cpp",
        "cpp/lib_ams/stream.cpp",
        "include/gen/lib_ams_gen.h",
        "include/gen/lib_ams_gen.inl.h",
        "include/lib_ams.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-llz4",
        "-lrt",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_library(
    name = "lib_ctype",
    srcs = [
        "cpp/gen/lib_ctype_gen.cpp",
        "cpp/lib/lib_ctype.cpp",
        "include/gen/lib_ctype_gen.h",
        "include/gen/lib_ctype_gen.inl.h",
        "include/lib_ctype.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_amcdb",
    ],
)

cc_library(
    name = "lib_exec",
    srcs = [
        "cpp/gen/lib_exec_gen.cpp",
        "cpp/lib/lib_exec.cpp",
        "include/gen/lib_exec_gen.h",
        "include/gen/lib_exec_gen.inl.h",
        "include/lib_exec.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_fm",
    srcs = [
        "cpp/gen/lib_fm_gen.cpp",
        "cpp/lib/lib_fm.cpp",
        "include/gen/lib_fm_gen.h",
        "include/gen/lib_fm_gen.inl.h",
        "include/lib_fm.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_library(
    name = "lib_git",
    srcs = [
        "cpp/gen/lib_git_gen.cpp",
        "cpp/lib/lib_git.cpp",
        "include/gen/lib_git_gen.h",
        "include/gen/lib_git_gen.inl.h",
        "include/lib_git.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_iconv",
    srcs = [
        "cpp/gen/lib_iconv_gen.cpp",
        "cpp/lib/lib_iconv.cpp",
        "include/gen/lib_iconv_gen.h",
        "include/gen/lib_iconv_gen.inl.h",
        "include/lib_iconv.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_json",
    srcs = [
        "cpp/gen/lib_json_gen.cpp",
        "cpp/lib/lib_json.cpp",
        "include/gen/lib_json_gen.h",
        "include/gen/lib_json_gen.inl.h",
        "include/lib_json.h",
        "include/lib_json.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_mysql",
    srcs = [
        "cpp/gen/lib_mysql_gen.cpp",
        "cpp/lib/lib_mysql.cpp",
        "include/gen/lib_mysql_gen.h",
        "include/gen/lib_mysql_gen.inl.h",
        "include/lib_mysql.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-lmariadb",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_prot",
    srcs = [
        "cpp/gen/ams_gen.cpp",
        "cpp/gen/amsdb_gen.cpp",
        "cpp/gen/atf_gen.cpp",
        "cpp/gen/atfdb_gen.cpp",
        "cpp/gen/fm_gen.cpp",
        "cpp/gen/fmdb_gen.cpp",
        "cpp/gen/gclidb_gen.cpp",
        "cpp/gen/ietf_gen.cpp",
        "cpp/gen/lib_prot_gen.cpp",
        "include/gen/ams_gen.h",
        "include/gen/ams_gen.inl.h",
        "include/gen/amsdb_gen.h",
        "include/gen/amsdb_gen.inl.h",
        "include/gen/atf_gen.h",
        "include/gen/atf_gen.inl.h",
        "include/gen/atfdb_gen.h",
        "include/gen/atfdb_gen.inl.h",
        "include/gen/fm_gen.h",
        "include/gen/fm_gen.inl.h",
        "include/gen/fmdb_gen.h",
        "include/gen/fmdb_gen.inl.h",
        "include/gen/gclidb_gen.h",
        "include/gen/gclidb_gen.inl.h",
        "include/gen/lib_prot_gen.h",
        "include/gen/lib_prot_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":lib_json",
    ],
)

cc_library(
    name = "lib_sql",
    srcs = [
        "cpp/gen/lib_sql_gen.cpp",
        "cpp/lib/lib_sql.cpp",
        "include/gen/lib_sql_gen.h",
        "include/gen/lib_sql_gen.inl.h",
        "include/lib_sql.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_library(
    name = "lib_sqlite",
    srcs = [
        "cpp/gen/lib_sqlite_gen.cpp",
        "cpp/lib_sqlite/lib_sqlite.cpp",
        "cpp/lib_sqlite/vtab.cpp",
        "extern/sqlite-3470000/sqlite3.c",
        "extern/sqlite-3470000/sqlite3.h",
        "include/gen/lib_sqlite_gen.h",
        "include/gen/lib_sqlite_gen.inl.h",
        "include/lib_sqlite.h",
    ],
    copts = [
        "-DSQLITE_DQS=0",
        "-DSQLITE_THREADSAFE=0",
        "-Iextern/sqlite-3470000",
        "-Wno-implicit-fallthrough",
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ctype",
        ":lib_prot",
    ],
)

cc_binary(
    name = "mdbg",
    srcs = [
        "cpp/gen/mdbg_gen.cpp",
        "cpp/mdbg/mdbg.cpp",
        "include/gen/mdbg_gen.h",
        "include/gen/mdbg_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "mysql2ssim",
    srcs = [
        "cpp/gen/mysql2ssim_gen.cpp",
        "cpp/mysql2ssim.cpp",
        "include/gen/mysql2ssim_gen.h",
        "include/gen/mysql2ssim_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-L /usr/lib64/mysql",
    ],
    deps = [
        ":algo_lib",
        ":lib_mysql",
    ],
)

cc_binary(
    name = "orgfile",
    srcs = [
        "cpp/gen/orgfile_gen.cpp",
        "cpp/orgfile.cpp",
        "include/gen/orgfile_gen.h",
        "include/gen/orgfile_gen.inl.h",
        "include/orgfile.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "samp_meng",
    srcs = [
        "cpp/gen/samp_meng_gen.cpp",
        "cpp/samp_meng/samp_meng.cpp",
        "include/gen/samp_meng_gen.h",
        "include/gen/samp_meng_gen.inl.h",
        "include/samp_meng.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_prot",
    ],
)

cc_binary(
    name = "samp_regx",
    srcs = [
        "cpp/gen/samp_regx_gen.cpp",
        "cpp/samp_regx/samp_regx.cpp",
        "include/gen/samp_regx_gen.h",
        "include/gen/samp_regx_gen.inl.h",
        "include/samp_regx.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "sandbox",
    srcs = [
        "cpp/gen/sandbox_gen.cpp",
        "cpp/sandbox.cpp",
        "include/gen/sandbox_gen.h",
        "include/gen/sandbox_gen.inl.h",
        "include/sandbox.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "src_func",
    srcs = [
        "cpp/gen/src_func_gen.cpp",
        "cpp/src_func/edit.cpp",
        "cpp/src_func/fileloc.cpp",
        "cpp/src_func/header.cpp",
        "cpp/src_func/iffy.cpp",
        "cpp/src_func/list.cpp",
        "cpp/src_func/main.cpp",
        "cpp/src_func/nextfile.cpp",
        "cpp/src_func/scan.cpp",
        "include/gen/src_func_gen.h",
        "include/gen/src_func_gen.inl.h",
        "include/src_func.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "src_hdr",
    srcs = [
        "cpp/gen/src_hdr_gen.cpp",
        "cpp/src_hdr/hdr.cpp",
        "include/gen/src_hdr_gen.h",
        "include/gen/src_hdr_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_git",
    ],
)

cc_binary(
    name = "src_lim",
    srcs = [
        "cpp/gen/src_lim_gen.cpp",
        "cpp/src_lim/lim.cpp",
        "include/gen/src_lim_gen.h",
        "include/gen/src_lim_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "ssim2csv",
    srcs = [
        "cpp/gen/ssim2csv_gen.cpp",
        "cpp/ssim2csv.cpp",
        "include/gen/ssim2csv_gen.h",
        "include/gen/ssim2csv_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "ssim2mysql",
    srcs = [
        "cpp/gen/ssim2mysql_gen.cpp",
        "cpp/ssim2mysql.cpp",
        "include/gen/ssim2mysql_gen.h",
        "include/gen/ssim2mysql_gen.inl.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
        "-L /usr/lib64/mysql",
    ],
    deps = [
        ":algo_lib",
        ":lib_mysql",
    ],
)

cc_binary(
    name = "ssimfilt",
    srcs = [
        "cpp/gen/ssimfilt_gen.cpp",
        "cpp/ssimfilt.cpp",
        "include/gen/ssimfilt_gen.h",
        "include/gen/ssimfilt_gen.inl.h",
        "include/ssimfilt.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_ctype",
        ":lib_json",
    ],
)

cc_binary(
    name = "strconv",
    srcs = [
        "cpp/gen/strconv_gen.cpp",
        "cpp/strconv/strconv.cpp",
        "include/gen/strconv_gen.h",
        "include/gen/strconv_gen.inl.h",
        "include/strconv.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
    ],
)

cc_binary(
    name = "sv2ssim",
    srcs = [
        "cpp/gen/sv2ssim_gen.cpp",
        "cpp/sv2ssim.cpp",
        "include/gen/sv2ssim_gen.h",
        "include/gen/sv2ssim_gen.inl.h",
        "include/sv2ssim.h",
    ],
    copts = [
        "-Wno-invalid-offsetof",
        "-Wno-unused-local-typedefs",
        "-Wno-long-long",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-cast-function-type",
        "-Wsequence-point",
        "-Wno-multichar",
        "-Wall",
        "-Wshadow",
        "-pipe",
        "-Wextra",
        "-Winit-self",
        "-Wmissing-declarations",
        "-Winvalid-pch",
        "-Wno-vla",
        "-fpch-preprocess",
        "-Wno-class-memaccess",
        "-Wpedantic",
        "-msse4.2",
        "-D AOS_SSE42",
        "-fno-strict-aliasing",
        "-Werror",
    ],
    linkopts = [
        "-pthread",
        "-Wl,--gc-sections",
    ],
    deps = [
        ":algo_lib",
        ":lib_amcdb",
    ],
)

genrule(
    name = "runner",
    outs = ["runner.sh"],
    cmd = """
echo 'cd $$(dirname $$(readlink -f BUILD))' >> $@
echo $(location atf_comp) -build:N -ood:N '$$@' >> $@
    """,
    tools = [":atf_comp"],
)

sh_test(
    name = "atf_comp_tests",
    srcs = ["runner.sh"],
    args = [
        "-compdir:$(BINDIR)",
    ],
    data = [
        ":BUILD",
    ],
)
